# Generated by Django 5.1.5 on 2025-03-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_name', models.CharField(max_length=200)),
                ('S_roll_no', models.IntegerField(default=0)),
                ('S_address', models.CharField(max_length=200)),
            ],
        ),
    ]
