# Generated by Django 5.1.5 on 2025-03-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcrudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='S_address',
            new_name='s_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='S_name',
            new_name='s_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='S_roll_no',
            new_name='s_roll_no',
        ),
    ]
