# Generated by Django 5.1.5 on 2025-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcrudapp', '0002_rename_s_address_student_s_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
